export const pubblications = [
  {
    id: "1",
    location: "fiume freddo",
    region: "sicilia",
    postData: "02/04/2023",
    postUser: "peppe",
    img: "https://planetofhotels.com/guide/sites/default/files/styles/node__blog_post__bp_banner/public/2021-01/Kirkjufell-volcano.jpg",
    description: "bel posto",
    comments: [
      {
        user: "giggio",
        avatar: "GG",
        avatarColor: "blue",
        text: "Ci sono stato anche io!",
      },
      {
        user: "albertino",
        avatar: "AA",
        avatarColor: "red",
        text: "come sei stato?",
      },
      {
        user: "giggiolone",
        avatar: "GI",
        avatarColor: "green",
        text: "grandissimo!",
      },
    ],
  },
  {
    id: "2",
    location: "ariccia",
    region: "lazio",
    postData: "03/03/2023",
    postUser: "pippo",
    img: "https://free4kwallpapers.com/uploads/originals/2015/10/02/nice-place.jpg",
    description: "La porchetta è buona",
    comments: [
      { user: "giggio", avatar: "GG", avatarColor: "blue", text: "Si è vero!" },
      {
        user: "albertino",
        avatar: "AA",
        avatarColor: "red",
        text: "No non è vero",
      },
    ],
  },
  {
    id: "62d1d49c-2fc4-4503-bbff-8bace8ede93b",
    location: "fiume freddo",
    region: "sicilia",
    postData: "02/04/2023",
    postUser: "peppe",
    img: "https://planetofhotels.com/guide/sites/default/files/styles/node__blog_post__bp_banner/public/2021-01/Kirkjufell-volcano.jpg",
    description: "bel posto",
    comments: [],
  },
  {
    id: "9676d011-61e9-41a1-b5b4-5180ec1aa9bb",
    location: "fiume freddo",
    region: "sicilia",
    postData: "02/04/2023",
    postUser: "peppe",
    img: "https://planetofhotels.com/guide/sites/default/files/styles/node__blog_post__bp_banner/public/2021-01/Kirkjufell-volcano.jpg",
    description: "bel posto",
    comments: [],
  },
  {
    id: "91e16ceb-eeb1-4501-9c45-8c2234de0f35",
    location: "fiume freddo",
    region: "sicilia",
    postData: "02/04/2023",
    postUser: "peppe",
    img: "https://planetofhotels.com/guide/sites/default/files/styles/node__blog_post__bp_banner/public/2021-01/Kirkjufell-volcano.jpg",
    description: "bel posto",
    comments: [],
  },
];
