export const users = [
  {
    id: "1",
    username: "peppe",
    mail: "peppe.pappa@gmail.com",
    password: "ciaomamma",
    avatar: "PP",
    color: "red",
  },
  {
    id: "2",
    username: "pippo",
    mail: "pippo.pappa@gmail.com",
    password: "ciaozia",
    avatar: "PI",
    color: "green",
  },
  {
    id: "3",
    username: "giacomino",
    mail: "giacomino.gia@gmail.com",
    password: "bellazi",
    avatar: "GG",
    color: "black",
  },
  {
    id: "548a8019-9a7f-4a25-bf0e-ccb8a3a0d36b",
    username: "superman",
    mail: "e.e@e.com",
    password: "aaaaa",
    avatar: "PP",
    color: "blue",
  },
  {
    id: "16673390-42af-45c4-812f-5c68e006dee5",
    username: "supermanssss",
    mail: "eeee.e@e.com",
    password: "aaaaa",
    avatar: "PP",
    color: "blue",
  },
];
